name: CodeQL Analysis
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'javascript'  # 分析する言語を指定（例: javascript, python, java など）
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3